### ISSUE TITLE
Add layouts directory under _patterns

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#12]
To accommodate Twig's modularity I'd suggest adding a `layouts` directory under `_patterns`, between `organism` and `templates` this way:
```
patterns
|__00-atoms
|__01-molecules
|__02-organisms
|__03-layouts
|__04-templates
|__05-pages
```

The idea is to have general layout templates in `layouts` that are not really templates of pages, but rather micro layout components, which with be extended in templates using the `extends` and `embed` tags in `templates. Something along the lines of:

**03-layouts/baseLayout.twig:**

```twig
<header>
  {% block header %}
  {% endblock header %}
</header>

{% block content %}
{% endblock content %}

<footer>
  {% block footer %}
  {% endblock footer %}
</footer>
```

**03-layouts/fixedFluid.twig:**

```twig
  <div class="l-fixed-fluid-wrapper">
    <main class="l-fluid-column">
      {% block fluidCol %}
      {% endblock fluidCol %}
    </main>
  </div>
  <aside class="l-fixed-column">
      {% block fixedCol %}
      {% endblock fixedCol %}
  </aside>
```

**03-templates/articlePage.twig:**

```twig
{% extends `layouts-baseLayout` %}

{% block content %}
  {% embed `layouts-fixedFluid` %}
      {% block fluidCol %}
        ... content ...
      {% endblock fluidCol %}
      {% block fixedCol %}
        ... content ...
      {% endblock fixedCol %}

  {% endembed %}
{% endblock content %}

```

If this is to much of a break from the Mustache edition, I guess they could be included in either `oragnizms` or `templates`, but it makes sense to me from a Twig perspective and, I think, lives pretty well with Atomic Design principles.

**Comment by dmolsen** [comment]
@TxHawks -

Not too much of a break. I would put them at `05-` just because I don't think it really has anything to do with AD and is more about leveraging the template language. Hell, you don't even need the ordinal.  I'd even make sure they got hidden in the nav. 

Have you tried implementing layouts? You should just be able to create the folder and layouts and go to town. PL should keep happily working. PL doesn't know anything about AD. That's completely defined by the organization and naming convention that you use in `source/_patterns/`. Try renaming something and you'll see.

PS - Technically, the PHP version of Mustache has a [BLOCKS](https://github.com/bobthecow/mustache.php/wiki/BLOCKS-pragma) feature but it's not spec-compliant as far as I know.

**Comment by TxHawks** [comment]
I did implement layouts and it works great. Just wanted to suggest it to be part of the default directory layout, and maybe the demo so it can help users easily understand templating options and points to best practices.

I wouldn't mind it being `05-

Didn't know about blocks in the Mustache version. Whish I did a while back... It isn't anywhere in the documentation, right? Are there any other hidden Mustache features the Mustache version?

**Comment by dmolsen** [comment]
@TxHawks -

AD is in Brad's wheelhouse. I'm just an implementor ;) Since blocks and [filters](https://github.com/bobthecow/mustache.php/wiki/FILTERS-pragma) aren't spec-compliant in Mustache they're a little annoying to set-up. I never supported that in PL1. PL2 supports filters though I'm calling them helpers since you use the `addHelper()` method to make them work in Mustache. They're quite weak compared to Twig though. Tough to have filters in a template language that takes a strong stand on not having business logic in templates ;)

**Comment by bradfrost** [comment]
Hey @TxHawks,
Thanks for the extra info about all the Twig stuff. I've been following
from a distance and it looks really interesting.

> Just wanted to suggest it to be part of the default directory layout, and
maybe the demo so it can help users easily understand templating options
and points to best practices.

Feel free to set up a Twig-specific demo showcasing what you feel is the
best structure for working this way. However, adding a new layer definitely
won't be included into the default PL directory and the demo. Again, as
@dmolsen mentioned PL is super malleable, so the atomic design structure
can be modified, extended, or bulldozed completely. But the default atomic
design structure will continue to be the PL default.

On Sunday, March 1, 2015, Dave Olsen <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @TxHawks <https://github.com/TxHawks> -
>
> AD is in Brad's wheelhouse. I'm just an implementor ;) Since blocks and
> filters <https://github.com/bobthecow/mustache.php/wiki/FILTERS-pragma>
> aren't spec-compliant in Mustache they're a little annoying to set-up. I
> never supported that in PL1. PL2 supports filters though I'm calling them
> helpers since you use the addHelper() method to make them work in
> Mustache. They're quite weak compared to Twig though. Tough to have filters
> in a template language that takes a strong stand on not having business
> logic in templates ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pattern-lab/edition-php-twig-development/issues/12#issuecomment-76536332>
> .
>


-- 
__________________________________
Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by dmolsen** [comment]
@TxHawks -

Actually, I thought of a different way to tackle this so it doesn't affect the demo structure because these aren't "patterns." I could follow the organizational structure of "macros" and do something like `source/_layouts`. I do think we need a clear way to embrace the extension points of Twig since it has a whole lot more options than Mustache. They don't have to be required but they have to be accounted for.

**Comment by TxHawks** [comment]
Hey @bradfrost,
Makes perfect sense that it won't be part of the demo. It's very Twig-centric. 

@dmolsen - A clear and easy way to extend Twig in PL would be very exciting. An ability to easily add custom Twig filters and functions by just placing simple `php` files in a folder would be great. 

The `source/_layouts` directory is another issue though, as they are definitely not  extensions. On the one hand, it makes sense, and feels like and extension of the `_meta` directory idea. On the other hand, it's a bit different, as layouts actually need to be actively `extend`ed or `embed`ed in patterns. Placing them outside the `_patterns` directory may be confusing, I'm not sure.

Perhaps a better option could be `source/_patterns/_layouts`?

**Comment by bradfrost** [comment]
Twig-centric is a great band name.

__________________________________
Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by dmolsen** [comment]
@TxHawks -

I'm not sure how it'd be confusing. Not any more confusing than `source/_meta/` at least. I think for now we'll run with `source/_patterns/05-layouts` or whatever someone wants to set-up because we know that works. I would like a clear "best practice" at some point though. Hopefully more Drupal folks can chime in too.

And filters and functions make me a little queasy. Right now the same concept for Mustache requires an install via Composer and registration of the function with the PatternEngine. It's not "drop in a folder" and go. I'll have to play around but I don't want to have to rely on `eval()`.

**Comment by TxHawks** [comment]
@dmolsen -
It's not a huge deal, but `source/_layouts` could be slightly less obvious than `source/_meta`. From a user's perspective, `_meta` "just works". You don't extend it, you don't embed it, it just wraps all your partials "by itself". In that sense, layouts are more similar to pattern partials.

`source/_patterns/05-layouts` works out for me for the time being, but I agree that a clear best practice sohuld be established.

**Comment by dmolsen** [comment]
@TxHawks -

Got filters working. I guess the same technique can be used for functions and tests. The problem at the moment is that `_source` gets a little crowded. We could be looking at a project that has this possibly:

```
  source/
    |_ _annotations
    |_ _data
    |_ _filters
    |_ _functions
    |_ _layouts
    |_ _macros
    |_ _meta
    |_ _patterns
    |_ _tests
    |_ css
    |_ favicon.ico
    |_ fonts
    |_ images
    |_ js
    |_ styleguide
```

That's a little crowded. Maybe just a `source/_twig-components` with filters, functions, layouts, macros, and tests listed underneath would work better? Any other ideas?

**Comment by TxHawks** [comment]
@dmolsen -

Wow, great. I really didn't expect anything so soon after you said filters and functions make you queasy :). I should really buy you a beer.

So, are they just drop in directories after all? Should I `composer update pattern-lab/patternengine-php-twig`?

I think `source/_twig-components` makes sense for `_filters`, `_functions` `tests` (and theoretically `tags`, though that's probably overkill and more complicated), which are indeed extensions of Twig itself, while `_macros` and `_layouts` aren't.

Come to think about it, my earlier point about `_layouts` is also true for `_macros`, so in the least, they should stay under `source`. Just my two cents.

About that beer - any way to show my appreciation?

**Comment by dmolsen** [comment]
@TxHawks -

I haven't committed the feature yet. Trying to wrap my arms around all of the possibilities. I hadn't even considered `tags` but I should keep it mind. The same technique for `filters` should work for `tags`. Only difference is class loading :)

**Comment by dmolsen** [comment]
The final layout for `source/` directories in Twig-related projects will need to look like:

```
  source/
    |_ _annotations
    |_ _data
    |_ _layouts
    |_ _macros
    |_ _meta
    |_ _patterns
    |_ _twig-components
           |_ filters
           |_ functions
           |_ tags
           |_ tests
    |_ css
    |_ favicon.ico
    |_ fonts
    |_ images
    |_ js
    |_ styleguide
```

In this way layouts don't show up under `_patterns` though technically someone can still do that. Hopefully this layout gives the hint that they shouldn't do that. This layout will be used in the [Base StarterKit for Twig](https://github.com/pattern-lab/starterkit-twig-base). This is the StarterKit that will be installed if someone wants an empty starting point and uses the `php core/console --starterkit --init` command.
