### ISSUE TITLE
Update path

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#14]
What is be the best way to update when there is a new release?

`composer update pattern-lab/core`? or do I need to do `composer update pattern-lab/edition-development-twig`?

**Comment by dmolsen** [comment]
@TxHawks -

We will have updates to components as opposed to one monolithic update. For example, `pattern-lab/core` and `pattern-lab/patternengine-twig` are both components. The Editions should be considered projects and their (_very thin_) code is not updatable via Composer. You have two options:

* run `composer update` and let every component in your project check for updates
* run `composer update pattern-lab/[component-name]` and update a specific component

For the most part I believe the project dependencies (_including what we will do with Pattern Lab_) use [semantic versioning](http://semver.org). This means running the first option should be fairly safe. For example, I've done a lot of work in the Twig PatternEngine. To update it specifically you'd run:

    composer update pattern-lab/patternengine-twig

Since you're running the Development Edition you're going to get whatever is in the `dev` branches for components. This should be considered unstable. I try to be good and only push working code to `dev` but that doesn't mean it's completely vetted, documented, or finished. As you've seen ;)

The [Standard Edition for Twig](https://github.com/pattern-lab/edition-php-twig-standard) is my attempt to release a more stable, based-on-real-releases Edition of Pattern Lab. Fingers crossed I finish the documentation for that and its related components today :)

**Comment by TxHawks** [comment]
If it's useful to you, for the time being I'm happy to keep using the dev edition for testing. Up to now nothing has been broken in a major way and you've been super responsive and helpful, so it's not a problem

**Comment by dmolsen** [comment]
@TxHawks -

Use what you like :) I'm very appreciative of the feedback.
