### ISSUE TITLE
Named arguments in macros

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#17]
According to [twigphp/Twig#1139](https://github.com/twigphp/Twig/pull/1139), named arguments are supported in macros.

However, when I try to do something like:

```twig
{# _macro/marco.macro.twig #}
{% macro test(a, b = 'bar') -%}
{{ a ? a : ""  }}{{ b }}
{%- endmacro %}
```

```twig
{# some-pattern inside _patterns #}
{{ macro.test(b='foo') }}
```

I get the following error:

```
Warning: Command failed: PHP Fatal error:  Uncaught exception 'Twig_Error_Syntax' with message 'Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",")
```

This seems similar to [twigphp/Twig#933](https://github.com/twigphp/Twig/pull/933), just that an explicit import does not work either (I placed the macro under the `_patterns` dir in order to check this).

**Comment by dmolsen** [comment]
@TxHawks -

Not in a position to quickly debug but check the version of Twig first. If you open the `composer.lock` file and do a search for `twig/twig` it should tell you what's installed. I think it might be old. You can then compare that version number against https://packagist.org/packages/twig/twig. If it's old you can run `composer update twig/twig` and see if it addresses your issue.

**Comment by TxHawks** [comment]
@dmolsen -

The installed version of Twig was a bit old, but that doesn't seem to be the issue. Upgraded from `1.15.1` to `1.18`, but still same behavior as reported above, albeit with a nicer error message due to the Twig version update.

Also, when I updated pattern-lab/core, I noticed that the `markdown`, `jsonlint` and several symfony packages were downgraded. Was this intended?

**Comment by dmolsen** [comment]
@TxHawks -

I think what you've found is an unsupported or "theoretical" syntax. While there are definitely issues open that refer to that format I can't find it in the docs. If you see something in official documentation that refers to that method of named arguments I can look more deeply at what PL might be doing to mess it up but for now... it's not a bug with either PL or Twig. The syntax you provided just plain isn't supported. FWIW, here's a working example:

```
{# _macro/marco.macro.twig #}
{% macro test(a, b = 'bar') -%}
{{ a ? a : ""  }} {{ b }}
{%- endmacro %}
```

```
{# some-pattern inside _patterns #}
{{ macro.test('foo') }}
```

The trick is that it sets `a` and not `b` but, from my standpoint as a programmer, that should be the expected behavior. So the output is:

    foo bar

As for downgrading... I made the dependencies "looser" in `dev` in an effort to properly support updates to components that supported semantic versioning. It appears that composer's `~` character doesn't quite work the way I expected. I'll probably end up changing that back at some point to better match `master` branch where I had to go with the explicit versions just to get the Standard Edition for Twig to load properly. In the short-term it shouldn't affect anything.

**Comment by redreinard** [comment]
I'm perplexed by this. The linked commit https://github.com/twigphp/Twig/pull/1139 had the exact message of "Added support for named arguments for macros". The documentation at http://twig.sensiolabs.org/doc/templates.html#named-arguments doesn't explicitly mention Macro's but also doesn't exclude them. 

If this isn't a supported feature (I expected the same behavior and found this looking for why it wasn't working), then the documentation should be clear about this, and not just blanket state "support for named arguments".
