### ISSUE TITLE
Pseudo patterns data inheritance is too broad

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#18]
The way pseudo patterns redefine default data is to specific.

If i have the following in `article.json`:

```json
{
  "authors": [
    {
      "name": "John Doe",
      "location": "Somewhere"
    },
    {
      "name": "Jane Doe",
      "location": "Someplace"
    },
  ]
}
```
and then this in `article~pseudo.json`:
```json
{
  "authors": [
    {
      "name": "Milhouse Van Houten",
    },
  ]
}
```

the `article pseudo` pattern will be rendered as if its data is:
```json
{
  "authors": [
    {
      "name": "Milhouse Van Houten",
      "location": "Somewhere"
    },
    {
      "name": "Jane Doe",
      "location": "Someplace"
    },
  ]
}
```
Meaning `authors` isn't overwritten. This seems pretty counter intuitive to me, and not very scaleable.

**Comment by bradfrost** [comment]
I've worked around this issue by only including one (or some other small number) item in the array and then in the override add more items if necessary. 

That doesn't solve the issue of totally overriding the array, but just thought I'd share how I deal with that.

**Comment by TxHawks** [comment]
@bradfrost - 
Yeah, that's how I currently work around it as well, but it can be pretty limiting, especially with more complex patterns

**Comment by dmolsen** [comment]
@TxHawks -

I'm not going to change the default behavior. That said, an attribute at the top of the pseudo pattern (e.g. `"patternlab-replace": true` could make sure the back-end code uses `array_replace_recursive()` instead of `array_merge_recursive()`. That's about as smart as I can make it. It's an either/or choice though. Either a key exists in both and the data is merged or a key exists in both and the data is replaced.

**Comment by TxHawks** [comment]
Perfect

**Comment by dmolsen** [comment]
@TxHawks -

FWIW, I spent some time looking into this and it's not possible. Sorry.

**Comment by TxHawks** [comment]
@dmolsen -
Thanks for the effort. Have already gotten used to working around this
