### ISSUE TITLE
Pattern specific annotations 

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-twig-development#9]
Is it possible to create pattern-specific annotations? I think I remember reading something about it, but can't find any reference to it.

**Comment by dmolsen** [comment]
@TxHawks -

It's not pattern-specific annotations but pattern-specific descriptions via YAML/Markdown. So if you have a pattern in `atoms/general/colors.mustache` you can add `atoms/general/colors.md` with the following:

```
---
title: pattern title
---
description for the pattern written in markdown
```

In the various views (e.g. code panel, view all) a title and description should get written out. Technically you can stick whatever key/value pairs you want in the front-matter but it doesn't get styled very well. Doing this from memory instead of testing. Sorry.
